# Generated by Django 5.1.8 on 2025-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trendyol_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="TrendyolProduct",
        ),
    ]
