# Generated by Django 5.1.8 on 2025-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trendyol_app", "0003_remove_trendyolproduct_cargo_company_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendyolAPIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_id",
                    models.CharField(max_length=100, verbose_name="Satıcı ID"),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                (
                    "base_url",
                    models.CharField(
                        default="https://apigw.trendyol.com/integration/",
                        max_length=255,
                        verbose_name="API Base URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif Mi?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trendyol API Konfigürasyonu",
                "verbose_name_plural": "Trendyol API Konfigürasyonları",
            },
        ),
        migrations.DeleteModel(
            name="APIConfig",
        ),
        migrations.RemoveField(
            model_name="trendyolproduct",
            name="batch_request",
        ),
        migrations.AlterModelOptions(
            name="trendyolproduct",
            options={
                "verbose_name": "Trendyol Ürünü",
                "verbose_name_plural": "Trendyol Ürünleri",
            },
        ),
        migrations.RemoveField(
            model_name="trendyolproduct",
            name="trendyol_brand_id",
        ),
        migrations.RemoveField(
            model_name="trendyolproduct",
            name="trendyol_category_id",
        ),
        migrations.AddField(
            model_name="trendyolproduct",
            name="batch_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Batch ID"
            ),
        ),
        migrations.AddField(
            model_name="trendyolproduct",
            name="batch_status",
            field=models.CharField(
                choices=[
                    ("pending", "Beklemede"),
                    ("processing", "İşleniyor"),
                    ("completed", "Tamamlandı"),
                    ("failed", "Başarısız"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Batch Durumu",
            ),
        ),
        migrations.AddField(
            model_name="trendyolproduct",
            name="cargo_company_id",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Kargo Firması ID"
            ),
        ),
        migrations.AddField(
            model_name="trendyolproduct",
            name="dimensional_weight",
            field=models.PositiveIntegerField(default=1, verbose_name="Desi"),
        ),
        migrations.AddField(
            model_name="trendyolproduct",
            name="last_check_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Son Kontrol Zamanı"
            ),
        ),
        migrations.AddField(
            model_name="trendyolproduct",
            name="status_message",
            field=models.TextField(blank=True, null=True, verbose_name="Durum Mesajı"),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="barcode",
            field=models.CharField(max_length=100, unique=True, verbose_name="Barkod"),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="brand_name",
            field=models.CharField(max_length=255, verbose_name="Marka Adı"),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="category_name",
            field=models.CharField(max_length=255, verbose_name="Kategori Adı"),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="currency_type",
            field=models.CharField(
                default="TRY", max_length=10, verbose_name="Para Birimi"
            ),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="description",
            field=models.TextField(verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="image_url",
            field=models.URLField(verbose_name="Resim URL"),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Liste Fiyatı"
            ),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="product_main_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Ürün Ana ID"
            ),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Stok Miktarı"),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Satış Fiyatı"
            ),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="stock_code",
            field=models.CharField(max_length=100, verbose_name="Stok Kodu"),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Başlık"),
        ),
        migrations.AlterField(
            model_name="trendyolproduct",
            name="vat_rate",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="KDV Oranı"
            ),
        ),
        migrations.DeleteModel(
            name="BatchRequest",
        ),
    ]
