# Generated by Django 5.1.8 on 2025-04-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CityConfiguration",
            fields=[
                (
                    "city_id",
                    models.CharField(
                        choices=[
                            ("866", "Adana"),
                            ("894", "Adıyaman"),
                            ("882", "Afyon"),
                            ("927", "Ağrı"),
                            ("920", "Aksaray"),
                            ("935", "Amasya"),
                            ("873", "Ankara"),
                            ("867", "Antalya"),
                            ("948", "Ardahan"),
                            ("905", "Artvin"),
                            ("871", "Aydın"),
                            ("885", "Balıkesir"),
                            ("939", "Bartın"),
                            ("925", "Batman"),
                            ("936", "Bayburt"),
                            ("917", "Bilecik"),
                            ("941", "Bingöl"),
                            ("897", "Bitlis"),
                            ("923", "Bolu"),
                            ("919", "Burdur"),
                            ("868", "Bursa"),
                            ("910", "Çanakkale"),
                            ("929", "Çankırı"),
                            ("888", "Çorum"),
                            ("874", "Denizli"),
                            ("926", "Diyarbakır"),
                            ("947", "Düzce"),
                            ("906", "Edirne"),
                            ("913", "Elazığ"),
                            ("922", "Erzincan"),
                            ("900", "Erzurum"),
                            ("887", "Eskişehir"),
                            ("890", "Gaziantep"),
                            ("884", "Giresun"),
                            ("943", "Gümüşhane"),
                            ("924", "Hakkari"),
                            ("877", "Hatay"),
                            ("914", "Iğdır"),
                            ("908", "Isparta"),
                            ("865", "İstanbul"),
                            ("872", "İzmir"),
                            ("898", "Kahramanmaraş"),
                            ("912", "Karabük"),
                            ("883", "Karaman"),
                            ("915", "Kars"),
                            ("895", "Kastamonu"),
                            ("869", "Kayseri"),
                            ("896", "Kırıkkale"),
                            ("902", "Kırklareli"),
                            ("940", "Kırşehir"),
                            ("876", "Kocaeli"),
                            ("875", "Konya"),
                            ("901", "Kütahya"),
                            ("893", "Malatya"),
                            ("891", "Manisa"),
                            ("930", "Mardin"),
                            ("903", "Mersin"),
                            ("899", "Muğla"),
                            ("932", "Muş"),
                            ("907", "Nevşehir"),
                            ("911", "Niğde"),
                            ("904", "Ordu"),
                            ("892", "Osmaniye"),
                            ("928", "Rize"),
                            ("870", "Sakarya"),
                            ("916", "Samsun"),
                            ("931", "Siirt"),
                            ("918", "Sinop"),
                            ("879", "Sivas"),
                            ("921", "Şanlıurfa"),
                            ("942", "Şırnak"),
                            ("880", "Tekirdağ"),
                            ("909", "Tokat"),
                            ("878", "Trabzon"),
                            ("937", "Tunceli"),
                            ("886", "Uşak"),
                            ("933", "Van"),
                            ("889", "Yalova"),
                            ("938", "Yozgat"),
                            ("881", "Zonguldak"),
                        ],
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="City ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "City Configuration",
                "verbose_name_plural": "City Configurations",
            },
        ),
        migrations.CreateModel(
            name="PriceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PRICE_THRESHOLD",
                    models.DecimalField(
                        decimal_places=2,
                        default=700.0,
                        max_digits=10,
                        verbose_name="Price Threshold (TRY)",
                    ),
                ),
                (
                    "BELOW_THRESHOLD_MULTIPLIER",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        max_digits=5,
                        verbose_name="Multiplier for Prices Below Threshold",
                    ),
                ),
                (
                    "ABOVE_THRESHOLD_MULTIPLIER",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=5,
                        verbose_name="Multiplier for Prices Above Threshold",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Price Configuration",
                "verbose_name_plural": "Price Configurations",
            },
        ),
        migrations.CreateModel(
            name="StockConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "STOCK_MAPPING",
                    models.JSONField(
                        default=dict,
                        help_text="JSON format: {'original_quantity': 'mapped_quantity'}",
                        verbose_name="Stock Quantity Mapping",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock Configuration",
                "verbose_name_plural": "Stock Configurations",
            },
        ),
    ]
