# Generated by Django 5.2 on 2025-04-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductListSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(default="", max_length=255)),
                ("last_modification", models.DateField(blank=True, null=True)),
                ("last_fetch", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Product List Source",
                "verbose_name_plural": "Product List Sources",
            },
        ),
        migrations.CreateModel(
            name="ProductUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                (
                    "change_frequency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("priority", models.CharField(blank=True, max_length=10, null=True)),
                ("lcw_last_modification", models.DateField(blank=True, null=True)),
                ("system_last_modification", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_urls",
                        to="product_list_api.productlistsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product URL",
                "verbose_name_plural": "Product URLs",
                "unique_together": {("source", "url")},
            },
        ),
    ]
