# Generated by Django 4.2.20 on 2025-04-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductSitemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        default="https://www.lcw.com/sitemap/api/FeedXml/TR/product_sitemap.xml"
                    ),
                ),
            ],
        ),
    ]
