# Generated by Django 5.2 on 2025-04-03 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_sitemap_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitemapSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        default="https://www.lcw.com/sitemap/api/FeedXml/TR/product_sitemap.xml",
                        max_length=255,
                    ),
                ),
                ("last_fetch", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Sitemap Source",
                "verbose_name_plural": "Sitemap Source",
            },
        ),
        migrations.CreateModel(
            name="SitemapUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                ("last_modification", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="product_sitemap_api.sitemapsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitemap URL",
                "verbose_name_plural": "Sitemap URLs",
                "unique_together": {("source", "url")},
            },
        ),
        migrations.DeleteModel(
            name="ProductSitemap",
        ),
    ]
