"""
Django settings for databridge project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8_a4y9samfh^6l3^z$p6e@f4y^nh2lq+w^557rdf9amu&o4s5)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold_app", # Third part but admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third part Apps
    "django_celery_beat",
    "rest_framework",
    "django_apscheduler",

    #####################################################################
    # Local Apps
    ## scraper_apps
    ### scraper_apps.lcwaikiki
    "scraper_apps.lcwaikiki.product_sitemap_api",
    "scraper_apps.lcwaikiki.product_list_api",
    "scraper_apps.lcwaikiki.product_api",

    "markets.trendyol_app",
    "config",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "databridge.urls"
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Or your preferred broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "databridge.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



PROXY_LIST = [
    "http://zkcqmduo:wg1ks7uapqib@64.137.57.16:6025",
    "http://zkcqmduo:wg1ks7uapqib@216.173.103.151:6665",
    "http://zkcqmduo:wg1ks7uapqib@45.38.122.204:7112",
    "http://zkcqmduo:wg1ks7uapqib@89.42.8.61:5622",
    "http://zkcqmduo:wg1ks7uapqib@45.43.70.89:6376",
    "http://zkcqmduo:wg1ks7uapqib@45.92.77.217:6239",
    "http://zkcqmduo:wg1ks7uapqib@104.239.90.91:6482",
    "http://zkcqmduo:wg1ks7uapqib@173.239.219.112:6021",
    "http://zkcqmduo:wg1ks7uapqib@185.245.26.233:6750",
    "http://zkcqmduo:wg1ks7uapqib@198.46.246.23:6647",
    "http://zkcqmduo:wg1ks7uapqib@145.223.56.208:7260",
    "http://zkcqmduo:wg1ks7uapqib@104.239.10.32:5703",
    "http://zkcqmduo:wg1ks7uapqib@154.92.124.254:5282",
    "http://zkcqmduo:wg1ks7uapqib@194.32.82.79:6724",
    "http://zkcqmduo:wg1ks7uapqib@45.117.55.249:6895",
    "http://zkcqmduo:wg1ks7uapqib@103.76.117.75:6340",
    "http://zkcqmduo:wg1ks7uapqib@150.107.224.158:6073",
    "http://zkcqmduo:wg1ks7uapqib@154.203.39.121:5409",
    "http://zkcqmduo:wg1ks7uapqib@173.244.41.204:6388",
    "http://zkcqmduo:wg1ks7uapqib@181.214.13.127:5968",
    "http://zkcqmduo:wg1ks7uapqib@107.172.221.21:5976",
    "http://zkcqmduo:wg1ks7uapqib@145.223.50.195:6257",
    "http://zkcqmduo:wg1ks7uapqib@173.211.30.136:6570",
    "http://zkcqmduo:wg1ks7uapqib@192.154.250.169:5749",
    "http://zkcqmduo:wg1ks7uapqib@23.94.7.39:5726",
    "http://zkcqmduo:wg1ks7uapqib@82.24.245.238:8061",
    "http://zkcqmduo:wg1ks7uapqib@104.168.8.179:5632",
    "http://zkcqmduo:wg1ks7uapqib@199.180.8.131:5842",
    "http://zkcqmduo:wg1ks7uapqib@45.131.102.11:5663",
    "http://zkcqmduo:wg1ks7uapqib@82.22.215.91:7422",
    "http://zkcqmduo:wg1ks7uapqib@82.27.246.171:7495",
    "http://zkcqmduo:wg1ks7uapqib@82.29.226.43:7385",
    "http://zkcqmduo:wg1ks7uapqib@192.95.91.117:5744",
    "http://zkcqmduo:wg1ks7uapqib@206.41.169.21:5601",
    "http://zkcqmduo:wg1ks7uapqib@92.113.242.171:6755",
    "http://zkcqmduo:wg1ks7uapqib@198.105.101.31:5660",
    "http://zkcqmduo:wg1ks7uapqib@64.137.79.140:6054",
    "http://zkcqmduo:wg1ks7uapqib@82.23.213.120:6960",
    "http://zkcqmduo:wg1ks7uapqib@91.212.74.45:6411",
    "http://zkcqmduo:wg1ks7uapqib@92.112.165.196:6648",
    "http://zkcqmduo:wg1ks7uapqib@23.26.61.73:5539",
    "http://zkcqmduo:wg1ks7uapqib@45.61.96.151:6131",
    "http://zkcqmduo:wg1ks7uapqib@89.213.141.79:6955",
    "http://zkcqmduo:wg1ks7uapqib@89.213.188.190:6066",
    "http://zkcqmduo:wg1ks7uapqib@194.113.112.133:6028",
    "http://zkcqmduo:wg1ks7uapqib@104.238.38.154:6422",
    "http://zkcqmduo:wg1ks7uapqib@216.74.80.82:6654",
    "http://zkcqmduo:wg1ks7uapqib@46.202.67.170:6166",
    "http://zkcqmduo:wg1ks7uapqib@92.112.148.95:6540",
    "http://zkcqmduo:wg1ks7uapqib@46.202.67.39:6035",
    "http://zkcqmduo:wg1ks7uapqib@89.43.34.132:6149",
    "http://zkcqmduo:wg1ks7uapqib@89.45.125.181:5907",
    "http://zkcqmduo:wg1ks7uapqib@155.254.48.128:6034",
    "http://zkcqmduo:wg1ks7uapqib@161.123.131.128:5733",
    "http://zkcqmduo:wg1ks7uapqib@31.58.30.210:6792",
    "http://zkcqmduo:wg1ks7uapqib@173.211.8.28:6140",
    "http://zkcqmduo:wg1ks7uapqib@103.114.59.241:7018",
    "http://zkcqmduo:wg1ks7uapqib@104.238.38.34:6302",
    "http://zkcqmduo:wg1ks7uapqib@104.252.149.240:5654",
    "http://zkcqmduo:wg1ks7uapqib@46.202.78.58:5553",
    "http://zkcqmduo:wg1ks7uapqib@84.33.47.158:7194",
    "http://zkcqmduo:wg1ks7uapqib@137.59.5.195:6678",
    "http://zkcqmduo:wg1ks7uapqib@145.223.63.159:6219",
    "http://zkcqmduo:wg1ks7uapqib@168.199.132.243:6315",
    "http://zkcqmduo:wg1ks7uapqib@104.239.105.182:6712",
    "http://zkcqmduo:wg1ks7uapqib@104.252.193.24:5934",
    "http://zkcqmduo:wg1ks7uapqib@140.99.201.221:6100",
    "http://zkcqmduo:wg1ks7uapqib@192.95.91.171:5798",
    "http://zkcqmduo:wg1ks7uapqib@92.112.165.47:6499",
    "http://zkcqmduo:wg1ks7uapqib@174.140.254.63:6654",
    "http://zkcqmduo:wg1ks7uapqib@82.27.246.59:7383",
    "http://zkcqmduo:wg1ks7uapqib@92.112.172.19:6291",
    "http://zkcqmduo:wg1ks7uapqib@168.199.141.138:5890",
    "http://zkcqmduo:wg1ks7uapqib@185.171.255.171:6224",
    "http://zkcqmduo:wg1ks7uapqib@198.105.122.148:6721",
    "http://zkcqmduo:wg1ks7uapqib@45.43.70.84:6371",
    "http://zkcqmduo:wg1ks7uapqib@82.23.243.164:7522",
    "http://zkcqmduo:wg1ks7uapqib@104.239.80.57:5635",
    "http://zkcqmduo:wg1ks7uapqib@154.92.125.176:5477",
    "http://zkcqmduo:wg1ks7uapqib@104.239.38.139:6672",
    "http://zkcqmduo:wg1ks7uapqib@188.215.5.145:5175",
    "http://zkcqmduo:wg1ks7uapqib@45.61.122.116:6408",
    "http://zkcqmduo:wg1ks7uapqib@82.24.221.104:5955",
    "http://zkcqmduo:wg1ks7uapqib@104.222.167.212:6614",
    "http://zkcqmduo:wg1ks7uapqib@184.174.28.112:5127",
    "http://zkcqmduo:wg1ks7uapqib@46.203.45.50:6073",
    "http://zkcqmduo:wg1ks7uapqib@86.38.234.140:6594",
    "http://zkcqmduo:wg1ks7uapqib@89.43.34.247:6264",
    "http://zkcqmduo:wg1ks7uapqib@161.123.115.250:5271",
    "http://zkcqmduo:wg1ks7uapqib@192.95.91.36:5663",
    "http://zkcqmduo:wg1ks7uapqib@188.68.1.181:6050",
    "http://zkcqmduo:wg1ks7uapqib@206.127.212.121:6099",
    "http://zkcqmduo:wg1ks7uapqib@5.154.253.176:8434",
    "http://zkcqmduo:wg1ks7uapqib@64.137.90.16:5636",
    "http://zkcqmduo:wg1ks7uapqib@23.129.252.172:6440",
    "http://zkcqmduo:wg1ks7uapqib@64.137.73.197:5285",
    "http://zkcqmduo:wg1ks7uapqib@84.33.47.72:7108",
    "http://zkcqmduo:wg1ks7uapqib@103.99.33.253:6248",
    "http://zkcqmduo:wg1ks7uapqib@64.43.89.52:6311",
    "http://zkcqmduo:wg1ks7uapqib@43.245.117.16:5600"
]

CURRENTLY_API_VERSION = "v1"

UNFOLD = {
    "DASHBOARD_CALLBACK": "unfold_app.views.dashboard_callback",
}

